### PR TITLE
Set tag max length to 20 chars

### LINKED ISSUE #276: [PE-D][Tester E] No length restriction on tags
There is no length restriction on tags. When a tag name is very long, it renders outside the UI boundary and is abruptly cut off mid-text, with no indication to the user that the full tag name is not visible. This means the user cannot see the full tag they added, and may not even realise the tag name has been truncated, making it harder to search for or manage tags later.

Steps to reproduce: 

add n/Google r/SWE d/15-03-2026 s/Pending t/averyveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylongggggggggggggggggtaggggggggggggggg

Expected: Tag name is truncated gracefully within the UI boundary (e.g. with ellipsis) or an error is shown when the tag name exceeds a reasonable length
Actual: Tag overflows outside the UI boundary and is abruptly cut off with no indication that the full name is not shown

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #287: [PE-D][Tester A] UI - Typing an extra long tag (>100 char) will result in the tag overflowing the UI box
Try:
`add n/Grab r/Backend Developer Intern d/01-03-2026 s/Pending e/johnd@example.com w/https://johndoe.example.com a/311, Clementi Ave 2, #02-25 t/000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 t/BigTech`

Image

The blue tag for the large 0s will overflow its UI component box.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #317: [PE-D][Tester B] Tags overflow and overlap into adjacent application cards when there are long tag names
Image

When an application has a long tag name, the tags overflow beyond the application card boundary and visually overlap into adjacent application cards, making the UI difficult to read.

Steps to reproduce:
Run add n/Test r/Dev d/01-01-2026 s/Pending t/tag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtagtag1tagtagtagtagtagtagtagtag
Observe that the tags overflow beyond the card boundary and overlap into the next application card

Expected: Tags should wrap within the application card boundary, or be truncated, so that the card layout remains clean and readable.

Actual: Tags extend beyond the card boundary and overlap into adjacent cards, making the UI difficult to read.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by JamieLoh**
Fixes #276 
Fixes #287 
Fixes #317

### CODE REVIEW

File: src/main/java/seedu/address/model/tag/Tag.java [hunk 1]
```diff
@@ -9,8 +9,9 @@
  */
 public class Tag {
 
-    public static final String MESSAGE_CONSTRAINTS = "Tags names should be alphanumeric";
-    public static final String VALIDATION_REGEX = "\\p{Alnum}+";
+    public static final String MESSAGE_CONSTRAINTS =
+            "Tags names should be alphanumeric and must not exceed 20 characters.";
+    public static final String VALIDATION_REGEX = "\\p{Alnum}{1,20}";
```
Comment (kinyean) [inline src/main/java/seedu/address/model/tag/Tag.java:15]: LGTM
