### PR TITLE
Fix error message discrepency

### LINKED ISSUE #264: [PE-D][Tester D] Mismatch between error message requirement and User Guide
Image

Image

The error message in the app only suggests using a positive index number but does not include that it also has to be within the
bounds of the current list as stated in the UG

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by kinyean**
Fixes #264

### CODE REVIEW

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 1]
```diff
@@ -76,44 +76,49 @@ public void initialize() {
 
         helpMessage.getChildren().addAll(section("edit",
                 "Update an application by its list number.",
-                "edit INDEX [n/COMPANY_NAME] [r/ROLE] [e/EMAIL] [w/WEBSITE] "
-                        + "[a/ADDRESS] [d/DATE] [s/STATUS] [t/TAG]...",
-                "At least one field must be provided.",
+                "edit INDEX FIELD [FIELD]...",
```
Comment (Leomarbel) [inline src/main/java/seedu/address/ui/HelpWindow.java:79]: LGTM

**Review by Leomarbel — APPROVED** [review]
