### PR TITLE
 Fix summary window auto-refresh

### LINKED ISSUE #285: [PE-D][Tester A] UI / Logic - Summary box keeps resurfacing when using any command that modifies state
From the following steps:
1. Type `summary`
2. Minimise `summary` window
3. Type in any valid `find` (e.g. `find n/`)
4. Summary window will always pop up and resurface in front of the main application

Image

As this behaviour is not extended to notes / help window, I believe this behaviour is unintended. Additionally, it may disrupt a user's experience with the application as the user has to keep minimising the summary window if they want to concurrently have the summary window open while using `find` commands.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by Kemango**
## Changes         

  - Added isAutoRefreshingSummary boolean flag to MainWindow
  - Updated refreshSummary() to set the flag before executing the summary command
  - Updated processCommandResult() to route to refreshSummaryContent() during auto-refresh, skipping toFront() and requestFocus()                                                                                   
  - Added refreshSummaryContent() to MainWindow to update summary window content without changing window focus or order                                                                                             
                                                                                                                                                                                                                    
 ## Result

  - Summary window no longer steals focus during add, edit, find, delete, etc.                                                                                                                                      
  - Summary window still opens and comes to front when the user explicitly types summary or uses the menu
  - Live content refresh still works correctly in the background              



Fix #285

### CODE REVIEW

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 1]
```diff
@@ -265,7 +265,7 @@ public void show() {
         Stage stage = getRoot();
 
         stage.setWidth(HELP_WINDOW_WIDTH);
-        stage.setWidth(HELP_WINDOW_HEIGHT);
+        stage.setHeight(HELP_WINDOW_HEIGHT);
```
Comment (NuowenQ) [inline src/main/java/seedu/address/ui/HelpWindow.java:268]: Nice catch!
