### PR TITLE
Modify company name and role message

### LINKED ISSUE #312: [PE-D][Tester B] Company name accepts special characters despite error message stating only alphanumeric characters and spaces are allowed
HireME accepts special characters in the company name field (e.g. $, @, !), despite the error message for invalid names explicitly stating "Names should only contain alphanumeric characters and spaces."

The error message - Names should only contain alphanumeric characters and spaces, and it should not be blank
was obtained when running command - add n/ r/ d/ s/

Steps to reproduce:
Run add n/$ r/Dev d/01-01-2026 s/Pending
Observe that the application is added successfully with company name $
Run add n/Google! r/Dev d/01-01-2026 s/Pending
Observe that the application is added successfully with company name Google!

Expected: An error message is shown stating that company names should only contain alphanumeric characters and spaces, consistent with what the error message describes.
Actual: Applications with special character company names are added successfully without any error or warning.
This is inconsistent, the error message describes a validation rule that is not actually enforced, which could mislead users about what inputs are valid.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #314: [PE-D][Tester B] Role field accepts special characters despite error message stating only alphanumeric characters and spaces are allowed
add n/Grab r/ d/ s/ produced this error message: Role should only contain alphanumeric characters and spaces, and it should not be blank

HireME accepts special characters in the role field (e.g. $, !), despite the error message for invalid roles explicitly stating "Names should only contain alphanumeric characters and spaces."

Steps to reproduce:
Run add n/Google r/$ d/01-01-2026 s/Pending
Observe that the application is added successfully with role $
Run add n/Google2 r/Dev! d/01-01-2026 s/Pending
Observe that the application is added successfully with role Dev!

Expected: An error message is shown stating that roles should only contain alphanumeric characters and spaces, consistent with what the error message describes.
Actual: Applications with special character roles are added successfully without any error or warning.
This is inconsistent, the error message describes a validation rule that is not actually enforced, which could mislead users about what inputs are valid.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by JamieLoh**
Fixes #314 
Fixes #312 

image
Screenshot 2026-04-12 192721

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -23,7 +23,7 @@ public class AddCommand extends Command {
 
     public static final String COMMAND_WORD = "add";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds an application to the address book. "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds an application to HireME. "
```
Comment (Leomarbel) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:26]: Nice catch

**Review by Leomarbel — APPROVED** [review]
